---
- name: update apt cache
  raw: apt update

- name: install python
  raw: apt install python python3 -y

- name: find initial kernel
  shell: uname -a
  register: dropletKernel 

- name: display kernel version
  debug:
    msg: "{{ dropletKernel }}"

- name: apt full upgrade
  apt:
    update_cache: yes
    upgrade: full

- name: restart droplet
  # https://github.com/ansible/ansible/issues/10472
  command: shutdown -r +1
  ignore_errors: True

- name: wait for droplet to finish restart
  local_action:
     module: wait_for
     host: "{{ inventory_hostname }}"
     state: started
     port: 22
     delay: 60
     timeout: 3200


