---
- name: create DigitalOcean droplet
  hosts: localhost
  tasks:
    - shell: ../python/digitalOceanDroplets.py create --name "TestFromAnsible" --droplet_size s-1vcpu-1gb --firewall --volume 10
    #- shell: ../python/digitalOceanDroplets.py create --name "TestFromAnsible" --droplet_size s-1vcpu-1gb
      register: dropletCreation

    - set_fact:
        #https://docs.ansible.com/ansible/2.5/user_guide/playbooks_filters.html#regular-expression-filters
        #for some reason, the script output is going into standard error ???
        dropletAddress: "{{dropletCreation.stderr | regex_findall('(?<=Droplet IP\\: )\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

    - debug:
        msg: "{{ dropletAddress[0] }}"

    - add_host: 
        hostname: "{{ dropletAddress[0] }}" 
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_user: root
        groups: createdDroplets

    - name: wait for droplet to be accessible
      wait_for: 
        host: "{{ dropletAddress[0] }}"
        state: started
        port: 22
        delay: 60
        timeout: 3200


- name: Droplet configuration
  hosts: createdDroplets
  # it appears that the Ubuntu 18.04 image from Digital Ocean 
  # does not contain Python, so the gathering facts fails.
  gather_facts: no
  roles:
    - dropletSetup 
